export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  marketplace: "/marketplace",
  marketplaceItem: (uuid: string) => `/marketplace/items/${uuid}`,
  myItems: "/my-items",
  myItemsNew: "/my-items/new",
  myItemsEdit: (uuid: string) => `/my-items/${uuid}/edit`,
  offers: "/offers",
  notifications: "/notifications",
  messages: "/messages",
  profile: "/profile",
  publicProfile: (uuid: string) => `/users/${uuid}`,
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    userDetail: (uuid: string) => `/admin/users/${uuid}`,
    roles: "/admin/roles",
    permissions: "/admin/permissions",
    system: "/admin/system",
  },
} as const;
