package com.barterplatform.domain.notification.enums;

public enum NotificationType {
    TRADE_OFFER_RECEIVED,
    TRADE_OFFER_ACCEPTED,
    TRADE_OFFER_COMPLETION_CONFIRMED,
    TRADE_OFFER_COMPLETED,
    TRADE_OFFER_REJECTED,
    TRADE_OFFER_CANCELLED,
    LISTING_REMOVED,
    LISTING_RESTORED
}

