plugins {
    id 'java-library'
}

dependencies {
    implementation project(':barter-api')
    implementation project(':barter-domain')
    implementation project(':barter-common')
    implementation project(':barter-infrastructure')

    implementation "org.mapstruct:mapstruct:${rootProject.ext.mapstructVersion}"
    implementation 'org.springframework.security:spring-security-crypto:6.5.0'

    api 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    compileOnly 'org.projectlombok:lombok:1.18.36'

    annotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.mapstructVersion}"
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    testImplementation 'org.mockito:mockito-junit-jupiter:5.12.0'
    testImplementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}

