#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOYMENT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMPOSE_FILE="${COMPOSE_FILE:-${DEPLOYMENT_DIR}/compose/docker-compose.dev.yml}"
ENV_FILE="${ENV_FILE:-${DEPLOYMENT_DIR}/env/dev.env}"
STATE_FILE="${STATE_FILE:-${DEPLOYMENT_DIR}/state/dev/latest.env}"
HEALTH_TIMEOUT_SECONDS="${HEALTH_TIMEOUT_SECONDS:-180}"
DRY_RUN="false"
SKIP_PULL="false"
BACKEND_IMAGE_OVERRIDE=""
FRONTEND_IMAGE_OVERRIDE=""

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Rolls back backend and/or frontend to previously captured image references without
restarting postgres or caddy, deleting volumes, or restoring the database.

Options:
  --state-file <file>     Deployment state file generated by capture-deployment-state.sh.
  --backend-image <ref>   Override backend rollback image (tag, digest, or local image ID).
  --frontend-image <ref>  Override frontend rollback image (tag, digest, or local image ID).
  --skip-pull             Do not pull missing rollback images from the registry.
  --dry-run               Print the actions without changing containers.
  --help                  Show this help.
EOF
}

fail() {
  echo "$*" >&2
  exit 1
}

print_command() {
  printf '  '
  printf '%q ' "$@"
  printf '\n'
}

run_cmd() {
  print_command "$@"

  if [[ "${DRY_RUN}" == "true" ]]; then
    return 0
  fi

  "$@"
}

compose_cmd() {
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" "$@"
}

is_image_id_ref() {
  [[ "$1" == sha256:* ]]
}

ensure_image_available() {
  local image_ref="$1"

  [[ -n "${image_ref}" ]] || fail "Internal error: image ref is empty."

  if [[ "${DRY_RUN}" == "true" ]]; then
    echo "[dry-run] Would ensure rollback image is available locally (pull if needed): ${image_ref}"
    return 0
  fi

  if docker image inspect "${image_ref}" >/dev/null 2>&1; then
    echo "Image already available locally: ${image_ref}"
    return 0
  fi

  if is_image_id_ref "${image_ref}"; then
    fail "Local image ID not found: ${image_ref}. Image-ID rollback requires the image to still exist on the host."
  fi

  if [[ "${SKIP_PULL}" == "true" ]]; then
    fail "Rollback image is not available locally and --skip-pull was set: ${image_ref}"
  fi

  echo "Pulling rollback image: ${image_ref}"
  run_cmd docker pull "${image_ref}"
}

wait_for_service_health() {
  local service="$1"
  local timeout_seconds="$2"
  local poll_interval=3
  local elapsed=0
  local container_id
  local health_status

  if [[ "${DRY_RUN}" == "true" ]]; then
    echo "[dry-run] Would wait up to ${timeout_seconds}s for '${service}' health."
    return 0
  fi

  echo "Waiting for '${service}' to become healthy after rollback (timeout: ${timeout_seconds}s)..."

  while (( elapsed < timeout_seconds )); do
    container_id="$(compose_cmd ps -q "${service}" | head -n 1)"

    if [[ -z "${container_id}" ]]; then
      sleep "${poll_interval}"
      elapsed=$((elapsed + poll_interval))
      continue
    fi

    health_status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "${container_id}" 2>/dev/null || true)"

    case "${health_status}" in
      healthy|running)
        echo "Service '${service}' is ${health_status}."
        return 0
        ;;
      unhealthy|exited|dead)
        fail "Service '${service}' entered '${health_status}' during rollback. Inspect logs with: docker compose --env-file ${ENV_FILE} -f ${COMPOSE_FILE} logs --tail=200 ${service}"
        ;;
      *)
        sleep "${poll_interval}"
        elapsed=$((elapsed + poll_interval))
        ;;
    esac
  done

  fail "Timed out after ${timeout_seconds}s waiting for '${service}' health during rollback. Inspect logs with: docker compose --env-file ${ENV_FILE} -f ${COMPOSE_FILE} logs --tail=200 ${service}"
}

rollback_service() {
  local service="$1"
  local image_ref="$2"

  echo
  echo "Recreating '${service}' with rollback image: ${image_ref}"
  case "${service}" in
    backend)
      run_cmd env BACKEND_IMAGE="${image_ref}" docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d --no-deps --force-recreate backend
      ;;
    frontend)
      run_cmd env FRONTEND_IMAGE="${image_ref}" docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d --no-deps --force-recreate frontend
      ;;
    *)
      fail "Unsupported rollback service: ${service}"
      ;;
  esac

  wait_for_service_health "${service}" "${HEALTH_TIMEOUT_SECONDS}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --state-file)
      STATE_FILE="${2:-}"
      shift 2
      ;;
    --backend-image)
      BACKEND_IMAGE_OVERRIDE="${2:-}"
      shift 2
      ;;
    --frontend-image)
      FRONTEND_IMAGE_OVERRIDE="${2:-}"
      shift 2
      ;;
    --skip-pull)
      SKIP_PULL="true"
      shift
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage >&2
      fail "Unknown argument: $1"
      ;;
  esac
done

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  fail "Missing compose file: ${COMPOSE_FILE}"
fi

if [[ ! -f "${ENV_FILE}" ]]; then
  fail "Missing env file: ${ENV_FILE}"
fi

if [[ "${DRY_RUN}" != "true" ]] && ! command -v docker >/dev/null 2>&1; then
  fail "Docker is not installed or not on PATH."
fi

if [[ -f "${STATE_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${STATE_FILE}"
else
  if [[ -z "${BACKEND_IMAGE_OVERRIDE}" && -z "${FRONTEND_IMAGE_OVERRIDE}" ]]; then
    fail "Rollback state file not found: ${STATE_FILE}
Run ${SCRIPT_DIR}/capture-deployment-state.sh before deployment, or pass --backend-image/--frontend-image explicitly."
  fi
fi

TARGET_BACKEND_IMAGE="${BACKEND_IMAGE_OVERRIDE:-${BACKEND_ROLLBACK_IMAGE:-}}"
TARGET_FRONTEND_IMAGE="${FRONTEND_IMAGE_OVERRIDE:-${FRONTEND_ROLLBACK_IMAGE:-}}"

if [[ -z "${TARGET_BACKEND_IMAGE}" && -z "${TARGET_FRONTEND_IMAGE}" ]]; then
  fail "No rollback images resolved. Provide a state file with BACKEND_ROLLBACK_IMAGE/FRONTEND_ROLLBACK_IMAGE or pass explicit --backend-image/--frontend-image values."
fi

echo "Using compose file: ${COMPOSE_FILE}"
echo "Using env file:     ${ENV_FILE}"
echo "Using state file:   ${STATE_FILE}"
echo "Dry run:            ${DRY_RUN}"

if [[ -n "${TARGET_BACKEND_IMAGE}" ]]; then
  echo "Backend rollback image:  ${TARGET_BACKEND_IMAGE}"
  ensure_image_available "${TARGET_BACKEND_IMAGE}"
fi

if [[ -n "${TARGET_FRONTEND_IMAGE}" ]]; then
  echo "Frontend rollback image: ${TARGET_FRONTEND_IMAGE}"
  ensure_image_available "${TARGET_FRONTEND_IMAGE}"
fi

if [[ -n "${TARGET_BACKEND_IMAGE}" ]]; then
  rollback_service backend "${TARGET_BACKEND_IMAGE}"
fi

if [[ -n "${TARGET_FRONTEND_IMAGE}" ]]; then
  rollback_service frontend "${TARGET_FRONTEND_IMAGE}"
fi

echo
echo "Rollback service status:"
run_cmd docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" ps

echo
echo "Rollback completed. PostgreSQL, Caddy, Docker volumes, and Azure Blob item images were left unchanged."
echo "Database restore remains a separate manual recovery step and was NOT run by this script."

